ytmdesktop/ytmdesktop

main.js
on minimizing the window and opening it back didn't use to focus on the page, therefore it didn't use to take any inputs from the keyboard.
=> * onFocus was missing.

package.json
Fix #52 
The latest version of electron builder has no support for Mac OS 32 bit so it's necessary to switch to a 64 bit build.
=> Change mac publish to use 64 bit electron builder

main.js
A temporary fix to the issue #67.
This is a known issue on all Chromium-based browsers due to the recent changes that Google is rolling out. More info at https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html
The bug was replicable by almost all users on other Electron applications such as Google Play Music Desktop Application, etc.
Current Fix:
- Using the latest Mozilla Firefox's User Agent on the main browser window instead of the Chromium's default one.
Files Changed:
- main.js
=> Fix: Unsafe browser on Login with User Agent

pages/settings/settings.html
There is a `tr.json` in `locales` folder but not added to select menu.
=> Added tr localization to language options

src/providers/trayProvider.js
#195 
Apply scaling for tray icon on macOS
Also, slightly refactor code:
- Remove redunant set of icon in setShinyTray method as we already did it in createTray
- Move nativeImageIcon building to separate method to reuse it
=> :bug: fix incorrect size on mac tray icon

src/providers/trayProvider.js
Notifications about new song playing may distract. In GPM desktop, for example, such notifications are silent.
=> :lipstick: Make next song notifications silent

main.js, src/providers/scrobblerProvider.js
This adds support for "Now Playing" feature on last.fm
Also fixes issue where if one track is on repeat, it would scrobble it only once. So now on top of "track change" it also tracks "current track started playing from the beginning".
=> :sparkles: support "Now Playing" for last.fm

README.md
Fix clone instructions to use new repo URL
=> Fix clone instructions to use new repo URL

main.js, src/assets/css/styles.css, src/utils/calcYTViewSize.js
✨ Apply accent color changes from player page to 'nice' title bar. (Color will not apply to system title bars)
🐛 Fix issue where 'continue where you left off' setting would not apply the accent color changes to the first song played on startup.
🐛 'Nice' titlebar now disappears correctly when a video or song goes fullscreen
📱 Increase height of 'nice' title bar to remove stray border, change default color to match the top bar of YTM, #232323.
✏️ Remove stray HSL debug statement from previous PR.
=> ✨ Accent Color Enhancements and Bugfixes

src/providers/infoPlayerProvider.js
Fix JS error in `updateActivity` by making `infoPlayerProvider.getPlayerInfo()` and `infoPlayerProvider.getTrackInfo()` actually return the player and track, respectively. These had been broken by a refactor in  b15b2ff.
=> :bug: JavaScript Errors in updateActivity

package-lock.json, package.json, yarn.lock
Use unpublished fork of scribble that correctly scrobbles albums
The only downside to this is that the git repo may be deleted at any moment (very unlikely to happen).
https://github.com/dittodhole/node-scribble-js/tree/a2b37f585c5382863319115db36201399477ed43
=> Scrobble albums

electron-builder-deploy64.yml, src/providers/mprisProvider.js
Made MPRIS handlers work when the app is snapped. Added MPRIS slot to electron builder config. Renamed MPRIS player name to match default MPRIS slot. Rework player MPRIS metadata to work with new name.
Addresses #443
=> Make MPRIS work with Ubuntu snapped version

src/providers/infoPlayerProvider.js
Last month I created pull request #374. Part of that improvement was the removal of the 5% increments on the volume slider.
Something broke since then and it is now impossible to control the volume to more than 1% accuracy. This means that it is impossible to set the volume to 0.5% or 1.5%.
This fix removes the 1% increments.
=> :bug: Fix stepless volume control

main.js, src/providers/mprisProvider.js
This allows to open the window when the player is in the  notification area and you click on it to show it again (GNOME 3 for example).
=> Allows raising of player

main.js, src/locales/en.json, src/utils/injectControls.js
This adds a button next to the settings button that allows to close the player completely. This is the best placement I found even though it might be better to add it to the popup menu that opens when you click your usericon. Unfortunately I was not able to do that, so if you want that there you will have to point me in the right direction
Fixes #418
=> Adds shutdown button

src/pages/settings/settings.js
Fix for the regression introduced in #416
The function context was changed due to moving to arrow function so I fixed this part.
As now `null` is passed as the fn parameter I removed the check on undefined and added a check before the callback call.
=> Fix settings are not saved bug

src/utils/injectControls.js
Fix double wheel scroll.
During usage, I found that if I focus on the volume slider and scroll wheel the volume is increased twice(see gif below). So if I scroll wheel once it increases/decreases volume by 10% instead of 5. It repros for percent increasing so to test this you need to disable dB volume by default (#374).
It happens because the event called two times: from youtube music(a default one) + custom event from `playerBarScrollToChangeVolume`.
I added checks on element hover(for both expanded and common slider) and now if the spinner has hovered then the app doesn't raise the second volume-change event.
I disabled this check for the dB feature as it will break its functionality. Also, I see a UI bug with enabled dB feature when I scroll wheel focusing on slider: the slider is …
=> Fix double wheel scrolling on volume

src/utils/calcYTViewSize.js
The main window has a wrong left-padding on Linux that can be seen when you're using a light YT theme.
The proposed PR fixes this
=> :bug: wrong left-padding in main window on linux

src/utils/injectControls.js
I used to maintain `google-music-electron` and was surprised there wasn't a forward button for the back button. This PR resolves that. In this PR:
- Added forward navigation button next to back navigation button
Bonus:
- Not in this PR but it shouldn't be too hard to implement disable logic: https://github.com/twolfson/google-music-electron/blob/2.20.0/lib/browser.js#L77-L91
Screenshots:
**Before:**
**After:**
=> :sparkles: added forward navigation

main.js
This is a fix that makes the mpris service startup only when necessary (a fix for LInux). 
Before the fix the controls showed upas soon as the program started which makes no sense since there is no media playing yet  (I only tried GNOME but I strongly suspect also other DEs). Now the player shows up in the notification area only after music starts playing
=> Use mpris only as soon as media is playing

package-lock.json, package.json, yarn.lock
I've been using ytmdesktop with v11 electron for a while and it has been fine.
With this patch, `npm outdated` looks like this:
```
~/src/ytmdesktop $ npm outdated
Package       Current  Wanted         Latest  Location
node-vibrant    3.1.5   3.1.6  3.2.1-alpha.1  youtube-music-desktop-app
pretty-quick    2.0.2   2.0.2          3.1.0  youtube-music-desktop-app
scribble        0.0.5     git            git  youtube-music-desktop-app
socket.io       2.3.0   2.4.1          3.0.5  youtube-music-desktop-app
```
I figure major version updates can be done in a separate PR
Related to #559
=> Update electron to v11 and other minor dep updates

main.js
change last.fm scrobble value to 20% track progress instead of 1%.
Avoids excessive scrobbling of tracks that get skipped.
=> Update last.fm scrobble value main.js

src/providers/trayProvider.js
Hi there,
I got exception "error is not defined" when the app open.
Made this simple changes to fix the issues. Also adding condition in the so the code doesn't throw exception when tray is null.
=> Fix error not defined message at start up

.github/ISSUE_TEMPLATE/bug_report.md
I've noticed some people making issues saying 1.14.0 even though it hasn't been released yet, and I assume their using the development branch.
I'm making this pull request to add a comment in the bug report template that tells the user to include the commit hash of the build they're on to make it easier for us to pin point issues
=> Add development branch note

main.js
Chromium / electron seem to write all streamed media to disk needlessly by default, this PR seeks to disable that.
By way of comparison these are stats from launching, searching and playing the first 3 mins of a video:-
Caching on:-
Caching Off :-
if you listen to music continuously during the work day this is over 4GB of unnecessary writes.
A similar flag was added to chrome to reduce battery usage caused by constant disk writes specifically for streaming media - so that should also be a pleasant side effect of this PR - though I won't claim to have proof.
=> Disable disk caching option

main.js
Related to #740
Fixes the continue where you left off setting where it couldn't correctly save the queue. YouTube Music exposes an element that provides the session link for the currently playing song and playlist together so instead of using the window URL as it previously was, it will use that. Do note I made it so if session link isn't found it will default to the behavior it was doing before which is saving the current window URL.
Known issues:
-  Radio and autoplay queues aren't saved. This is upstream to YouTube Music and cannot be fixed.
=> 🐛 Fix continue where you left off

src/providers/discordRpcProvider.js
Discord has finally added support of being able to use Custom Links within Rich Presences allowing for us to be able to display the Album Art of the current song in the Large image!
A Long awaited feature implemented. 😍
Large Profile:
Small profile:
=> ✨ Add Album to Rich Presences' Large Picture

main.js, src/pages/miniplayer/miniplayer.css, src/pages/miniplayer/miniplayer.html, src/pages/miniplayer/miniplayer.js, src/pages/miniplayer/streamPlayer.css, src/pages/miniplayer/streamPlayer.html, src/pages/settings/settings.css, src/pages/settings/settings.html, src/pages/settings/settings.js, src/utils/defaultSettings.js
ONCE MORE, WITH FEELING
Many "Now Playing" music widgets for use in OBS/XSplit usually require multiple third party services or software programs, and more often than not only have support for Spotify or web-hosted music streaming. Additionally, due to the information passing between multiple APIs it is common for the information displayed to not be accurate or sufficient. This feature is intended to be a baked-in solution for the YouTube Music Desktop Application, by shuffling around the existing elements of the Miniplayer for more optimized screen space and information display. I have added a toggle in the Miniplayer settings menu, which will load alternate HTML/CSS files that play nicely with these streaming tools, as well as a tooltip on the toggle to indicate to the user settings …
=> ✨ Alternate Miniplayer Stream Widget

.github/workflows/build.yml
Pin to macos-11 since mscos-12 don't have python2 which will cause build fail.
=> 💚  Pin workflow macos build environment to `macos-11`

README.md
Currently, clicking on the Discord and License widget gives you error 404 because the syntax is wrong. Quick fix
=> 📝 Fix Discord invite and License in README.md

.github/workflows/publish.yml
=> Disable Windows ARM64 Build Publishes in GHA

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
Now that ARM64 builds are available since [v2.0.0-rc.4](../releases/tag/v2.0.0-rc.4) (via #1169), it seems appropriate to add ARM64 to the architecture options in the bug report form. Thus, this PR adds ARM64 option to the bug report form.
=> 📝 Add ARM64 to Bug Report Template

src/renderer/windows/settings/Settings.vue
This Pull Request improves readability of the companions table.
Instead of squishing everything into 3 columns, reduce it to 2 columns and have id and name in the same `Companion` Column. This probably also improves word-wrap issues, because the id and name can now span across the row and due to the character limit, it won't wrap so extremely anymore or not not even at all.
And to better distinguish between the id and name, I made the id bold.
=> :lipstick: Improve readability of companions table
